package it.isa.progetto;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import java.lang.Integer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import java.util.List;
public class PANELCorsiClienti extends javax.swing.JPanel {

    /**
     * Creates new form PANELCorsiClienti
     */
    public PANELCorsiClienti(Cliente cliente, List<Corso> corsi) {
        initComponents(cliente,corsi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Cliente cliente, List<Corso> corsi) {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pannello=new TestPane();

        //brr:   this.cliente= cliente;

        setPreferredSize(new java.awt.Dimension(400, 300));
        setBackground(new java.awt.Color(243, 226, 243));

        jLabel1.setText("Tutti i corsi:");

        jLabel2.setText("Corsi a cui sei iscritto:");

        jButton1.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           // .addGap(0, 226, Short.MAX_VALUE)
           .addComponent(pannello, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGap(0, 255, Short.MAX_VALUE)
            .addComponent(pannello, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGap(0, 249, Short.MAX_VALUE)
            .addComponent(pannello, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           // .addGap(0, 0, Short.MAX_VALUE)
           .addComponent(pannello, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
           );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        //tutti i corsi
        for(int i=0; i<corsi.size(); i++)
        {
    
            JPanel panel = new JPanel();
            if(corsi.get(i).isDELETED().equals("N")){
            JButton button = new JButton(makeButtonText(corsi.get(i),cliente));
            button.setName(Integer.toString(corsi.get(i).getID_CO()));
            panel.add(button);
    
            // le prossime righe servono perchè quando clicco il bottone voglio che si elimini quel cliente
            button.addActionListener((ActionListener) this);
        
            //panel.setBorder(new MatteBorder(0, 0, 1, 0, Color.GRAY));       serve?
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridwidth = GridBagConstraints.REMAINDER;
            gbc.weightx = 1;
            gbc.fill = GridBagConstraints.HORIZONTAL;
            pannello.mainList.add(panel, gbc, 0);      
            }
        }
    
    validate();
    repaint();
    
    }// </editor-fold>                           
    
    //tutti i corsi
    public void actionPerformed(ActionEvent e ) {
        DAOFactory df= new DAOFactory();
        df.beginTransaction();
        CorsoDAO dao= df.getCorsoDAO();
       int ID_corso= (Integer.parseInt(((JButton)e.getSource()).getName()));
        if(dao.findCorsoCliente( ID_corso,  cliente.getID_CL())){
        } //se il cliente è gia iscritto a quel corso non faccio nulla 
        else {dao.createIscrizione(ID_corso,  cliente.getID_CL());}  
        //se no lo iscrivo ovvero creo nuova riga di iscrizione
        df.commitTransaction();
        df.closeTransaction();
            
        }
    
      //aggiunto da noi per il for:  per il i-esimo cliente con delted = N , creo il bottone per eliminarlo
      public String makeButtonText(Corso corsi)
      {
         
        return ("NOME: "+corsi.getNOME()+"\t TIPO: "+corsi.getTIPO()+"\t LIVELLO: "+corsi.getLIVELLO());
          
    
      }
    
      public class TestPane extends JPanel {
    
          private JPanel mainList;
    
          public TestPane() {
              setLayout(new BorderLayout());
    
              mainList = new JPanel(new GridBagLayout());
              GridBagConstraints gbc = new GridBagConstraints();
              gbc.gridwidth = GridBagConstraints.REMAINDER;
              gbc.weightx = 1;
              gbc.weighty = 1;
              mainList.add(new JPanel(), gbc);
    
              add(new JScrollPane(mainList));
    
          }
          
          @Override
          public Dimension getPreferredSize() {
              return new Dimension(200, 200);
          }
      }
                           


    // Variables declaration - do not modify                     
    javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private TestPane pannello;
    Cliente cliente;
    // End of variables declaration                   
}

